name: SwornGuns
main: net.dmulloy2.swornguns.SwornGuns
#version: ${project.version} (Build ${project.build.number})
version: ${project.version}
author: dmulloy2
description: Guns in Minecraft!
softdepend: [UltimateArena, SwornRPG]
commands: 
  swornguns:
    description: SwornGuns root command
    usage: /<command> <args>
    aliases: [gun, guns]
permissions:
  swornguns.*:
    description: Allows access to all SwornGuns features
    default: false
    children:
      swornguns.toggle: true
      sworngins.reload: true
  swornguns.reload:
    description: Lets you reload the plugin
    default: false
  swornguns.fire:
    description: Per-gun permissions
    default: op