name: SwornGuns
main: net.dmulloy2.swornguns.SwornGuns
version: "${project.version}"
author: dmulloy2
softdepend: [UltimateArena, SwornRPG]
commands: 
  swornguns:
    description: SwornGuns root command
    usage: /<command> <args>
    aliases: [guns]
permissions:
  swornguns.*:
    description: Allows access to all SwornGuns features
    default: false
    children:
      swornguns.toggle: true
      sworngins.reload: true
  swornguns.reload:
    description: Lets you reload the plugin
    default: false
  swornguns.fire:
    description: Per-gun permissions
    default: op